name: APK Derle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Izni Ver ve Derle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
